In [2]:
import pandas as pd
import numpy as np 
import re
import matplotlib.pyplot as plt

In [6]:
candidates = pd.read_csv('../webscraping_open_secrets-malted_milk_balls/candidates.csv')

In [7]:
candidates.head()

,Unnamed: 0,Name,Party,State,District Number,Incumbent Status,Winner Status,Percentage of Vote,Total Amount Raised,Total Amount Spent
0,0,Jerry Carl,(R),Alabama,District 01,N/a,Winner,64.9,1971321,1859349
1,1,James Averhart,(D),Alabama,District 01,N/a,N/a,35.0,80095,78973
2,2,Barry Moore,(R),Alabama,District 02,N/a,Winner,65.3,650807,669368
3,3,Phyllis Harvey-Hall,(D),Alabama,District 02,N/a,N/a,34.6,56050,55988
4,4,Mike D Rogers,(R),Alabama,District 03,Incumbent,Winner,67.5,1193111,1218564

In [8]:
candidates['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [9]:
AL = candidates['State'] == 'Alabama'
AK = candidates['State'] == 'Alaska'
AZ = candidates['State'] == 'Arizona'
AR = candidates['State'] == 'Arkansas'
CA = candidates['State'] == 'California'
CO = candidates['State'] == 'Colorado'
CT = candidates['State'] == 'Connecticut'
DE = candidates['State'] == 'Deleware'
FL = candidates['State'] == 'Florida'
GA = candidates['State'] == 'Georgia'
HI = candidates['State'] == 'Hawaii'
ID = candidates['State'] == 'Idaho'
IL = candidates['State'] == 'Illinois'
IN = candidates['State'] == 'Indiana'
IA = candidates['State'] == 'Iowa'
KS = candidates['State'] == 'Kansas'
KY = candidates['State'] == 'Kentucky'
LA = candidates['State'] == 'Louisiana'
ME = candidates['State'] == 'Maine'
MD = candidates['State'] == 'Maryland'
MA = candidates['State'] == 'Massachusetts'
MI = candidates['State'] == 'Michigan'
MN = candidates['State'] == 'Minnesota'
MS = candidates['State'] == 'Mississippi'
MO = candidates['State'] == 'Missouri'
MT = candidates['State'] == 'Montana'
NE = candidates['State'] == 'Nebraska'
NV = candidates['State'] == 'Nevada'
NH = candidates['State'] == 'New Hampshire'
NJ = candidates['State'] == 'New Jersey'
NM = candidates['State'] == 'New Mexico'
OR = candidates['State'] == 'Oregon'
PA = candidates['State'] == 'Pennsylvania'
RI = candidates['State'] == 'Rhode Island'
SC = candidates['State'] == 'South Carolina'
SD = candidates['State'] == 'South Dakota'
TN = candidates['State'] == 'Tennessee'
TX = candidates['State'] == 'Texas'
UT = candidates['State'] == 'Utah'
VT = candidates['State'] == 'Vermont'
VA = candidates['State'] == 'Virginia'
WA = candidates['State'] == 'Washington'
WV = candidates['State'] == 'West Virginia'
WI = candidates['State'] == 'Wisconsin'
WY = candidates['State'] == 'Wyoming'

In [10]:
states = candidates['State'].unique().tolist()
districts = candidates['District Number'].unique().tolist()
TAR = candidates['Total Amount Raised'].unique().tolist()
Winner = candidates['Winner Status'].unique().tolist()

In [11]:
candidates['State-District'] = candidates['State'] + " " + candidates['District Number']
candidates.head()

,Unnamed: 0,Name,Party,State,District Number,Incumbent Status,Winner Status,Percentage of Vote,Total Amount Raised,Total Amount Spent,State-District
0,0,Jerry Carl,(R),Alabama,District 01,N/a,Winner,64.9,1971321,1859349,Alabama District 01
1,1,James Averhart,(D),Alabama,District 01,N/a,N/a,35.0,80095,78973,Alabama District 01
2,2,Barry Moore,(R),Alabama,District 02,N/a,Winner,65.3,650807,669368,Alabama District 02
3,3,Phyllis Harvey-Hall,(D),Alabama,District 02,N/a,N/a,34.6,56050,55988,Alabama District 02
4,4,Mike D Rogers,(R),Alabama,District 03,Incumbent,Winner,67.5,1193111,1218564,Alabama District 03

In [12]:
question_1 = candidates[['State-District', 'Winner Status', 'Total Amount Raised']]
question_1

            State-District Winner Status  Total Amount Raised
0      Alabama District 01        Winner              1971321
1      Alabama District 01           N/a                80095
2      Alabama District 02        Winner               650807
3      Alabama District 02           N/a                56050
4      Alabama District 03        Winner              1193111
..                     ...           ...                  ...
887  Wisconsin District 07           N/a              1261957
888  Wisconsin District 08        Winner              3202905
889  Wisconsin District 08           N/a               416978
890    Wyoming District 01        Winner              3003883
891    Wyoming District 01           N/a               134597

[892 rows x 3 columns]

In [13]:
winner = question_1['Total Amount Raised'][question_1['Winner Status'] == 'Winner'].tolist()
loser = question_1['Total Amount Raised'][question_1['Winner Status'] == 'N/a'].tolist()

for i in question_1['State-District']:
    if (winner > loser) == True:
        print(i)

Alabama District 01
Alabama District 01
Alabama District 02
Alabama District 02
Alabama District 03
Alabama District 03
Alabama District 04
Alabama District 05
Alabama District 06
Alabama District 07
Alaska District 01
Alaska District 01
Arizona District 01
Arizona District 01
Arizona District 02
Arizona District 02
Arizona District 03
Arizona District 03
Arizona District 04
Arizona District 04
Arizona District 05
Arizona District 05
Arizona District 06
Arizona District 06
Arizona District 06
Arizona District 07
Arizona District 07
Arizona District 08
Arizona District 08
Arizona District 09
Arizona District 09
Arkansas District 01
Arkansas District 02
Arkansas District 02
Arkansas District 03
Arkansas District 03
Arkansas District 04
Arkansas District 04
California District 01
California District 01
California District 02
California District 02
California District 03
California District 03
California District 04
California District 04
California District 05
California District 06
California District 06
California District 07
California District 07
California District 08
California District 08
California District 09
California District 09
California District 10
California District 10
California District 11
California District 11
California District 12
California District 12
California District 13
California District 13
California District 14
California District 15
California District 16
California District 16
California District 17
California District 17
California District 18
California District 18
California District 19
California District 19
California District 20
California District 20
California District 21
California District 21
California District 22
California District 22
California District 23
California District 23
California District 24
California District 24
California District 25
California District 25
California District 26
California District 26
California District 27
California District 27
California District 28
California District 28
California District 29
California District 29
California District 30
California District 31
California District 31
California District 32
California District 32
California District 33
California District 33
California District 34
California District 34
California District 35
California District 35
California District 36
California District 36
California District 37
California District 37
California District 38
California District 39
California District 39
California District 40
California District 40
California District 41
California District 41
California District 42
California District 42
California District 43
California District 43
California District 44
California District 45
California District 45
California District 46
California District 47
California District 47
California District 48
California District 48
California District 49
California District 49
California District 50
California District 50
California District 51
California District 51
California District 52
California District 52
California District 53
California District 53
Colorado District 01
Colorado District 02
Colorado District 02
Colorado District 02
Colorado District 03
Colorado District 03
Colorado District 03
Colorado District 04
Colorado District 04
Colorado District 05
Colorado District 05
Colorado District 05
Colorado District 06
Colorado District 06
Colorado District 06
Colorado District 07
Colorado District 07
Colorado District 07
Connecticut District 01
Connecticut District 01
Connecticut District 02
Connecticut District 02
Connecticut District 03
Connecticut District 03
Connecticut District 03
Connecticut District 04
Connecticut District 04
Connecticut District 05
Connecticut District 05
Delaware District 01
Delaware District 01
Delaware District 01
Florida District 01
Florida District 01
Florida District 01
Florida District 02
Florida District 02
Florida District 03
Florida District 03
Florida District 04
Florida District 04
Florida District 05
Florida District 05
Florida District 06
Florida District 06
Florida District 06
Florida District 07
Florida District 07
Florida District 07
Florida District 08
Florida District 08
Florida District 09
Florida District 09
Florida District 10
Florida District 10
Florida District 10
Florida District 11
Florida District 11
Florida District 12
Florida District 12
Florida District 13
Florida District 13
Florida District 14
Florida District 14
Florida District 15
Florida District 15
Florida District 16
Florida District 16
Florida District 17
Florida District 17
Florida District 18
Florida District 18
Florida District 19
Florida District 19
Florida District 20
Florida District 20
Florida District 21
Florida District 21
Florida District 21
Florida District 22
Florida District 22
Florida District 23
Florida District 23
Florida District 24
Florida District 24
Florida District 24
Florida District 25
Florida District 26
Florida District 26
Florida District 27
Florida District 27
Florida District 27
Georgia District 01
Georgia District 01
Georgia District 02
Georgia District 02
Georgia District 03
Georgia District 03
Georgia District 04
Georgia District 04
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 05
Georgia District 06
Georgia District 06
Georgia District 07
Georgia District 07
Georgia District 08
Georgia District 08
Georgia District 08
Georgia District 09
Georgia District 09
Georgia District 10
Georgia District 10
Georgia District 11
Georgia District 11
Georgia District 12
Georgia District 12
Georgia District 13
Georgia District 13
Georgia District 13
Georgia District 14
Hawaii District 01
Hawaii District 01
Hawaii District 02
Hawaii District 02
Hawaii District 02
Idaho District 01
Idaho District 01
Idaho District 02
Idaho District 02
Illinois District 01
Illinois District 01
Illinois District 02
Illinois District 03
Illinois District 03
Illinois District 04
Illinois District 04
Illinois District 05
Illinois District 06
Illinois District 06
Illinois District 06
Illinois District 07
Illinois District 07
Illinois District 08
Illinois District 09
Illinois District 09
Illinois District 10
Illinois District 10
Illinois District 11
Illinois District 11
Illinois District 12
Illinois District 12
Illinois District 13
Illinois District 13
Illinois District 14
Illinois District 14
Illinois District 15
Illinois District 15
Illinois District 16
Illinois District 16
Illinois District 17
Illinois District 17
Illinois District 18
Indiana District 01
Indiana District 01
Indiana District 02
Indiana District 02
Indiana District 03
Indiana District 03
Indiana District 04
Indiana District 04
Indiana District 05
Indiana District 05
Indiana District 06
Indiana District 06
Indiana District 07
Indiana District 07
Indiana District 08
Indiana District 08
Indiana District 09
Indiana District 09
Indiana District 09
Iowa District 01
Iowa District 01
Iowa District 02
Iowa District 02
Iowa District 03
Iowa District 03
Iowa District 04
Iowa District 04
Kansas District 01
Kansas District 01
Kansas District 02
Kansas District 02
Kansas District 03
Kansas District 03
Kansas District 04
Kansas District 04
Kentucky District 01
Kentucky District 02
Kentucky District 02
Kentucky District 02
Kentucky District 03
Kentucky District 03
Kentucky District 04
Kentucky District 04
Kentucky District 05
Kentucky District 06
Kentucky District 06
Louisiana District 01
Louisiana District 02
Louisiana District 03
Louisiana District 03
Louisiana District 03
Louisiana District 04
Louisiana District 04
Louisiana District 05
Louisiana District 05
Louisiana District 05
Louisiana District 05
Louisiana District 05
Louisiana District 05
Louisiana District 05
Louisiana District 06
Louisiana District 06
Maine District 01
Maine District 01
Maine District 02
Maine District 02
Maryland District 01
Maryland District 01
Maryland District 02
Maryland District 02
Maryland District 03
Maryland District 03
Maryland District 04
Maryland District 05
Maryland District 05
Maryland District 06
Maryland District 06
Maryland District 07
Maryland District 07
Maryland District 07
Maryland District 08
Maryland District 08
Massachusetts District 01
Massachusetts District 02
Massachusetts District 02
Massachusetts District 03
Massachusetts District 04
Massachusetts District 04
Massachusetts District 05
Massachusetts District 05
Massachusetts District 06
Massachusetts District 06
Massachusetts District 07
Massachusetts District 08
Massachusetts District 09
Massachusetts District 09
Michigan District 01
Michigan District 01
Michigan District 02
Michigan District 02
Michigan District 02
Michigan District 03
Michigan District 03
Michigan District 04
Michigan District 04
Michigan District 05
Michigan District 05
Michigan District 06
Michigan District 06
Michigan District 07
Michigan District 07
Michigan District 08
Michigan District 08
Michigan District 09
Michigan District 10
Michigan District 10
Michigan District 11
Michigan District 11
Michigan District 12
Michigan District 12
Michigan District 13
Michigan District 13
Michigan District 14
Michigan District 14
Minnesota District 01
Minnesota District 01
Minnesota District 02
Minnesota District 02
Minnesota District 03
Minnesota District 03
Minnesota District 03
Minnesota District 04
Minnesota District 04
Minnesota District 05
Minnesota District 05
Minnesota District 05
Minnesota District 05
Minnesota District 06
Minnesota District 06
Minnesota District 07
Minnesota District 07
Minnesota District 08
Minnesota District 08
Mississippi District 01
Mississippi District 01
Mississippi District 02
Mississippi District 03
Mississippi District 04
Missouri District 01
Missouri District 02
Missouri District 02
Missouri District 03
Missouri District 04
Missouri District 04
Missouri District 05
Missouri District 05
Missouri District 06
Missouri District 06
Missouri District 07
Missouri District 07
Missouri District 08
Missouri District 08
Montana District 01
Montana District 01
Nebraska District 01
Nebraska District 01
Nebraska District 02
Nebraska District 02
Nebraska District 03
Nebraska District 03
Nevada District 01
Nevada District 02
Nevada District 02
Nevada District 03
Nevada District 03
Nevada District 04
Nevada District 04
Nevada District 04
New Hampshire District 01
New Hampshire District 01
New Hampshire District 02
New Hampshire District 02
New Jersey District 01
New Jersey District 01
New Jersey District 02
New Jersey District 02
New Jersey District 03
New Jersey District 03
New Jersey District 04
New Jersey District 04
New Jersey District 05
New Jersey District 05
New Jersey District 05
New Jersey District 06
New Jersey District 07
New Jersey District 07
New Jersey District 08
New Jersey District 09
New Jersey District 09
New Jersey District 10
New Jersey District 11
New Jersey District 11
New Jersey District 12
New Jersey District 12
New Mexico District 01
New Mexico District 01
New Mexico District 02
New Mexico District 02
New Mexico District 02
New Mexico District 03
New Mexico District 03
New York District 01
New York District 01
New York District 02
New York District 02
New York District 02
New York District 03
New York District 03
New York District 03
New York District 04
New York District 04
New York District 04
New York District 05
New York District 05
New York District 06
New York District 06
New York District 07
New York District 08
New York District 09
New York District 10
New York District 10
New York District 10
New York District 10
New York District 11
New York District 11
New York District 11
New York District 12
New York District 13
New York District 13
New York District 14
New York District 14
New York District 15
New York District 16
New York District 17
New York District 17
New York District 17
New York District 18
New York District 18
New York District 18
New York District 19
New York District 19
New York District 20
New York District 20
New York District 21
New York District 21
New York District 22
New York District 22
New York District 23
New York District 23
New York District 24
New York District 24
New York District 25
New York District 25
New York District 25
New York District 26
New York District 27
New York District 27
New York District 27
North Carolina District 01
North Carolina District 01
North Carolina District 02
North Carolina District 02
North Carolina District 02
North Carolina District 03
North Carolina District 04
North Carolina District 05
North Carolina District 05
North Carolina District 06
North Carolina District 06
North Carolina District 06
North Carolina District 07
North Carolina District 07
North Carolina District 08
North Carolina District 08
North Carolina District 09
North Carolina District 09
North Carolina District 10
North Carolina District 10
North Carolina District 11
North Carolina District 11
North Carolina District 12
North Carolina District 12
North Carolina District 13
North Carolina District 13
North Dakota District 01
North Dakota District 01
Ohio District 01
Ohio District 01
Ohio District 01
Ohio District 02
Ohio District 02
Ohio District 03
Ohio District 03
Ohio District 04
Ohio District 04
Ohio District 05
Ohio District 05
Ohio District 06
Ohio District 06
Ohio District 07
Ohio District 07
Ohio District 07
Ohio District 08
Ohio District 08
Ohio District 09
Ohio District 09
Ohio District 10
Ohio District 10
Ohio District 11
Ohio District 11
Ohio District 12
Ohio District 12
Ohio District 12
Ohio District 13
Ohio District 13
Ohio District 14
Ohio District 14
Ohio District 15
Ohio District 15
Ohio District 16
Ohio District 16
Oklahoma District 01
Oklahoma District 01
Oklahoma District 02
Oklahoma District 02
Oklahoma District 03
Oklahoma District 04
Oklahoma District 04
Oklahoma District 05
Oklahoma District 05
Oregon District 01
Oregon District 01
Oregon District 02
Oregon District 02
Oregon District 03
Oregon District 03
Oregon District 04
Oregon District 04
Oregon District 05
Oregon District 05
Pennsylvania District 01
Pennsylvania District 01
Pennsylvania District 02
Pennsylvania District 03
Pennsylvania District 04
Pennsylvania District 04
Pennsylvania District 04
Pennsylvania District 05
Pennsylvania District 05
Pennsylvania District 06
Pennsylvania District 06
Pennsylvania District 06
Pennsylvania District 07
Pennsylvania District 08
Pennsylvania District 08
Pennsylvania District 09
Pennsylvania District 09
Pennsylvania District 10
Pennsylvania District 10
Pennsylvania District 11
Pennsylvania District 11
Pennsylvania District 12
Pennsylvania District 12
Pennsylvania District 12
Pennsylvania District 13
Pennsylvania District 13
Pennsylvania District 14
Pennsylvania District 14
Pennsylvania District 15
Pennsylvania District 16
Pennsylvania District 16
Pennsylvania District 17
Pennsylvania District 17
Pennsylvania District 18
Pennsylvania District 18
Rhode Island District 01
Rhode Island District 02
Rhode Island District 02
South Carolina District 01
South Carolina District 01
South Carolina District 02
South Carolina District 02
South Carolina District 03
South Carolina District 03
South Carolina District 04
South Carolina District 04
South Carolina District 05
South Carolina District 05
South Carolina District 06
South Carolina District 07
South Carolina District 07
South Carolina District 07
South Dakota District 01
Tennessee District 01
Tennessee District 01
Tennessee District 02
Tennessee District 02
Tennessee District 03
Tennessee District 03
Tennessee District 04
Tennessee District 04
Tennessee District 05
Tennessee District 06
Tennessee District 07
Tennessee District 07
Tennessee District 07
Tennessee District 07
Tennessee District 08
Tennessee District 08
Tennessee District 09
Tennessee District 09
Tennessee District 09
Texas District 01
Texas District 01
Texas District 02
Texas District 02
Texas District 02
Texas District 03
Texas District 03
Texas District 04
Texas District 04
Texas District 05
Texas District 05
Texas District 05
Texas District 06
Texas District 06
Texas District 07
Texas District 07
Texas District 08
Texas District 08
Texas District 09
Texas District 09
Texas District 10
Texas District 10
Texas District 11
Texas District 11
Texas District 12
Texas District 12
Texas District 12
Texas District 13
Texas District 13
Texas District 14
Texas District 14
Texas District 14
Texas District 14
Texas District 15
Texas District 15
Texas District 16
Texas District 16
Texas District 17
Texas District 17
Texas District 17
Texas District 18
Texas District 18
Texas District 19
Texas District 19
Texas District 20
Texas District 20
Texas District 21
Texas District 21
Texas District 21
Texas District 22
Texas District 22
Texas District 23
Texas District 23
Texas District 24
Texas District 24
Texas District 24
Texas District 24
Texas District 24
Texas District 25
Texas District 25
Texas District 26
Texas District 26
Texas District 27
Texas District 27
Texas District 28
Texas District 28
Texas District 29
Texas District 29
Texas District 30
Texas District 30
Texas District 31
Texas District 31
Texas District 32
Texas District 32
Texas District 32
Texas District 33
Texas District 33
Texas District 34
Texas District 34
Texas District 35
Texas District 35
Texas District 35
Texas District 36
Texas District 36
Utah District 01
Utah District 01
Utah District 02
Utah District 02
Utah District 02
Utah District 03
Utah District 03
Utah District 03
Utah District 03
Utah District 04
Utah District 04
Utah District 04
Vermont District 01
Virginia District 01
Virginia District 01
Virginia District 02
Virginia District 02
Virginia District 03
Virginia District 03
Virginia District 04
Virginia District 04
Virginia District 05
Virginia District 05
Virginia District 06
Virginia District 06
Virginia District 07
Virginia District 07
Virginia District 08
Virginia District 08
Virginia District 08
Virginia District 09
Virginia District 10
Virginia District 10
Virginia District 11
Virginia District 11
Virginia District 11
Washington District 01
Washington District 01
Washington District 02
Washington District 02
Washington District 03
Washington District 03
Washington District 04
Washington District 04
Washington District 05
Washington District 05
Washington District 06
Washington District 06
Washington District 07
Washington District 07
Washington District 08
Washington District 08
Washington District 09
Washington District 09
Washington District 10
Washington District 10
West Virginia District 01
West Virginia District 01
West Virginia District 02
West Virginia District 02
West Virginia District 03
West Virginia District 03
West Virginia District 03
Wisconsin District 01
Wisconsin District 01
Wisconsin District 02
Wisconsin District 02
Wisconsin District 03
Wisconsin District 03
Wisconsin District 04
Wisconsin District 05
Wisconsin District 05
Wisconsin District 06
Wisconsin District 06
Wisconsin District 07
Wisconsin District 07
Wisconsin District 08
Wisconsin District 08
Wyoming District 01
Wyoming District 01

In [15]:
raised_pivot = (
    candidates
    .pivot_table(
        values = 'Total Amount Raised',
        index = 'State-District',
        columns = 'Winner Status'
    )
    .dropna()
)
raised_pivot

Winner Status                N/a     Winner
State-District
Alabama District 01      80095.0  1971321.0
Alabama District 02      56050.0   650807.0
Alabama District 03      50273.0  1193111.0
Alaska District 01     5178452.0  1922901.0
Arizona District 01    1675618.0  3381353.0
...                          ...        ...
Wisconsin District 05   370392.0  1155721.0
Wisconsin District 06   287753.0  1815756.0
Wisconsin District 07  1261957.0  2637459.0
Wisconsin District 08   416978.0  3202905.0
Wyoming District 01     134597.0  3003883.0

[371 rows x 2 columns]

In [16]:
raised_pivot['Raised_More'] = raised_pivot.apply(lambda x: x['Winner'] if x['Winner'] >=
                     x['N/a'] else np.nan, axis=1)
raised_pivot

Winner Status                N/a     Winner  Raised_More
State-District
Alabama District 01      80095.0  1971321.0    1971321.0
Alabama District 02      56050.0   650807.0     650807.0
Alabama District 03      50273.0  1193111.0    1193111.0
Alaska District 01     5178452.0  1922901.0          NaN
Arizona District 01    1675618.0  3381353.0    3381353.0
...                          ...        ...          ...
Wisconsin District 05   370392.0  1155721.0    1155721.0
Wisconsin District 06   287753.0  1815756.0    1815756.0
Wisconsin District 07  1261957.0  2637459.0    2637459.0
Wisconsin District 08   416978.0  3202905.0    3202905.0
Wyoming District 01     134597.0  3003883.0    3003883.0

[371 rows x 3 columns]

In [17]:
raised_pivot['Raised_More'].value_counts()

1971321.0    1
1090395.0    1
791888.0     1
1866123.0    1
1580952.0    1
            ..
544690.0     1
5582179.0    1
822846.0     1
2802093.0    1
3003883.0    1
Name: Raised_More, Length: 332, dtype: int64

In [18]:
raised_pivot.notna().sum()

Winner Status
N/a            371
Winner         371
Raised_More    332
dtype: int64

In [19]:
332/371

0.894878706199461

In [21]:
spent_pivot = (
    candidates
    .pivot_table(
        values = 'Total Amount Spent',
        index = 'State-District',
        columns = 'Winner Status'
    )
    .dropna()
)
spent_pivot

Winner Status                N/a     Winner
State-District
Alabama District 01      78973.0  1859349.0
Alabama District 02      55988.0   669368.0
Alabama District 03      40971.0  1218564.0
Alaska District 01     5088103.0  1790448.0
Arizona District 01    1615704.0  3324138.0
...                          ...        ...
Wisconsin District 05   371799.0   968406.0
Wisconsin District 06   245788.0  1736659.0
Wisconsin District 07  1232690.0  2514740.0
Wisconsin District 08   399916.0  2841801.0
Wyoming District 01     132235.0  3060167.0

[371 rows x 2 columns]

In [29]:
spent_pivot['Spent_More'] = spent_pivot.apply(lambda x: x['Winner'] if x['Winner'] >=
                     x['N/a'] else np.nan, axis=1)
spent_pivot

Winner Status                N/a     Winner  Spent_More
State-District
Alabama District 01      78973.0  1859349.0   1859349.0
Alabama District 02      55988.0   669368.0    669368.0
Alabama District 03      40971.0  1218564.0   1218564.0
Alaska District 01     5088103.0  1790448.0         NaN
Arizona District 01    1615704.0  3324138.0   3324138.0
...                          ...        ...         ...
Wisconsin District 05   371799.0   968406.0    968406.0
Wisconsin District 06   245788.0  1736659.0   1736659.0
Wisconsin District 07  1232690.0  2514740.0   2514740.0
Wisconsin District 08   399916.0  2841801.0   2841801.0
Wyoming District 01     132235.0  3060167.0   3060167.0

[371 rows x 3 columns]

In [30]:
spent_pivot['Spent_More'].value_counts()

1859349.0    1
979798.0     1
453928.0     1
1853361.0    1
1477090.0    1
            ..
1514838.0    1
505506.0     1
5313570.0    1
711159.0     1
3060167.0    1
Name: Spent_More, Length: 330, dtype: int64

In [31]:
spent_pivot.notna().sum()

Winner Status
N/a           371
Winner        371
Spent_More    330
dtype: int64

In [32]:
330/371

0.889487870619946

In [33]:
candidates.head()

,Unnamed: 0,Name,Party,State,District Number,Incumbent Status,Winner Status,Percentage of Vote,Total Amount Raised,Total Amount Spent,State-District
0,0,Jerry Carl,(R),Alabama,District 01,N/a,Winner,64.9,1971321,1859349,Alabama District 01
1,1,James Averhart,(D),Alabama,District 01,N/a,N/a,35.0,80095,78973,Alabama District 01
2,2,Barry Moore,(R),Alabama,District 02,N/a,Winner,65.3,650807,669368,Alabama District 02
3,3,Phyllis Harvey-Hall,(D),Alabama,District 02,N/a,N/a,34.6,56050,55988,Alabama District 02
4,4,Mike D Rogers,(R),Alabama,District 03,Incumbent,Winner,67.5,1193111,1218564,Alabama District 03

In [37]:
incumbent_pivot = (
    candidates
    .pivot_table(
        values = 'Total Amount Raised',
        index = 'State-District',
        columns = 'Incumbent Status'
    )
    .dropna()
)
incumbent_pivot

Incumbent Status       Incumbent        N/a
State-District
Alabama District 03    1193111.0    50273.0
Alaska District 01     1922901.0  5178452.0
Arizona District 01    3381353.0  1675618.0
Arizona District 02    1849862.0   374821.0
Arizona District 03     843560.0    41422.0
...                          ...        ...
Wisconsin District 03  2989262.0  1962443.0
Wisconsin District 06  1815756.0   287753.0
Wisconsin District 07  2637459.0  1261957.0
Wisconsin District 08  3202905.0   416978.0
Wyoming District 01    3003883.0   134597.0

[330 rows x 2 columns]

In [38]:
incumbent_pivot['Spent_More'] = incumbent_pivot.apply(lambda x: x['Incumbent'] if x['Incumbent'] >=
                     x['N/a'] else np.nan, axis=1)
incumbent_pivot

Incumbent Status       Incumbent        N/a  Spent_More
State-District
Alabama District 03    1193111.0    50273.0   1193111.0
Alaska District 01     1922901.0  5178452.0         NaN
Arizona District 01    3381353.0  1675618.0   3381353.0
Arizona District 02    1849862.0   374821.0   1849862.0
Arizona District 03     843560.0    41422.0    843560.0
...                          ...        ...         ...
Wisconsin District 03  2989262.0  1962443.0   2989262.0
Wisconsin District 06  1815756.0   287753.0   1815756.0
Wisconsin District 07  2637459.0  1261957.0   2637459.0
Wisconsin District 08  3202905.0   416978.0   3202905.0
Wyoming District 01    3003883.0   134597.0   3003883.0

[330 rows x 3 columns]

In [39]:
incumbent_pivot['Spent_More'].value_counts()

1193111.0    1
1269346.0    1
791888.0     1
1866123.0    1
1580952.0    1
            ..
1918041.0    1
2381354.0    1
3459512.0    1
1834801.0    1
3003883.0    1
Name: Spent_More, Length: 307, dtype: int64

In [40]:
incumbent_pivot.notna().sum()

Incumbent Status
Incumbent     330
N/a           330
Spent_More    307
dtype: int64

In [41]:
307/330

0.9303030303030303

In [91]:
question_d = candidates[['State-District', 'Winner Status', 'Incumbent Status']]

Winner = question_d['Incumbent Status'][question_d['Winner Status'] == 'Winner'].tolist()
incumbent_count = Winner.count('Incumbent')
newbie_count = Winner.count('N/a')
print('The count of Incumbent Winners: ', incumbent_count)
print('The count of Non-Incumbent Winners: ', newbie_count)

The count of Incumbent Winners:  371
The count of Non-Incumbent Winners:  60

In [94]:
371/431

0.8607888631090487

In [98]:
incumbent_pivot = (
    candidates
    .pivot_table(
        values = 'Total Amount Raised',
        index = 'State-District',
        columns = 'Incumbent Status'
    )
    .dropna()
)
incumbent_pivot

Incumbent Status       Incumbent        N/a
State-District
Alabama District 03    1193111.0    50273.0
Alaska District 01     1922901.0  5178452.0
Arizona District 01    3381353.0  1675618.0
Arizona District 02    1849862.0   374821.0
Arizona District 03     843560.0    41422.0
...                          ...        ...
Wisconsin District 03  2989262.0  1962443.0
Wisconsin District 06  1815756.0   287753.0
Wisconsin District 07  2637459.0  1261957.0
Wisconsin District 08  3202905.0   416978.0
Wyoming District 01    3003883.0   134597.0

[330 rows x 2 columns]

In [99]:
incumbent_pivot['Incumbent'].mean()

2908101.8575757574

In [100]:
incumbent_pivot['N/a'].mean()

1012913.4727272728

In [105]:
question_e = candidates[['Total Amount Raised', 'Incumbent Status']]
question_e

     Total Amount Raised Incumbent Status
0                1971321              N/a
1                  80095              N/a
2                 650807              N/a
3                  56050              N/a
4                1193111        Incumbent
..                   ...              ...
887              1261957              N/a
888              3202905        Incumbent
889               416978              N/a
890              3003883        Incumbent
891               134597              N/a

[892 rows x 2 columns]